### ISSUE TITLE
Average Energy Consumption figures incorrect since 22nd June

### ISSUE THREAD

**Issue by 3shirts** [pypolestar/polestar_api#148]
Since 22/06/24 the Average Energy Consumption number has dropped. It seems like it's a factor of 10 as I was getting around 22 (kWh/100km) before and now it's 0.2 or 0.3 though I notice it's not 0.2**2** it's only 1 decimal.

**Comment by leeyuentuen** [comment]
is it still the case? i saw here that the value is still correct

**Comment by 3shirts** [comment]
Yeah it's still screwy. Currently 0.6 instead of the real world 22

**Comment by knuckleheadsmiff** [comment]
I don’t think this has ever worked for me. I always see a number like 3.2kw/100km

(would also be nice to have the units in miles as a config option based on the unit measurements in the car for the odometer.)

**Comment by jschlyter** [comment]
How does this work in the current version @knuckleheadsmiff @3shirts ? My car reports correctly.

**Comment by knuckleheadsmiff** [comment]
It still seems way off.  Note the my car is set to miles not km but converting km to miles this number just can’t be correct. (See image)
![IMG_0935](https://github.com/user-attachments/assets/8e8b8d36-192d-498d-8c77-960ab7364288)

**Comment by jschlyter** [comment]
Seems to be an API issue as the reported values are fetched directly from `averageEnergyConsumptionKwhPer100Km` in backend API. Is the statistics in your mobile app correct?

**Comment by knuckleheadsmiff** [comment]
Mobile app shows “7.1kWh/100 mi” so the numbers seem to line up (although obviously bad) but it’s not this code.

**Comment by wouterhardeman** [comment]
Seems that this is an issue on Polestar's side since the data matches the app. 

At the time of your report they seemed to have performed some rollback on their database (possibly because they pushed a bad update at the time). For me they set my odometer about a month back which was resolved after driving again. It could be that your average consumption got messed up during that time.

I would recommend resetting your manual trip meter in the car. The average energy consumption is based on that. Drive around for a while and check if you get a more realistic value.

**Comment by knuckleheadsmiff** [comment]
Resetting the manual trip meter did indeed fix things.
