### ISSUE TITLE
Setting charge limit is now possible in app.

### ISSUE THREAD

**Issue by iambenmitchell** [pypolestar/polestar_api#149]
Just an FYI, not an issue but setting the charge limit is now possible in the iOS app. Hopefully it will be possible to add to this project too ;)

**Comment by olalid** [comment]
This integration can not access all the functions that the app can.
It is limited to access the functions/data that you can access when you log in on the polestar webpage.
See https://github.com/leeyuentuen/polestar_api/discussions/114

**Comment by motoridersd** [comment]
I've been doing the charge limit through HA, by monitoring the battery level that the API provides and stopping my EVSE when the target is reached. The car is set to 100% all the time so that HA can control it.

**Comment by sschimansky** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre E-Mail.

Ich bin bis zum 29. Juli 2024 nicht im Büro und habe nur beschränkten Zugriff auf meine E-Mails. 

Bitte wenden Sie sich in dringenden Fällen an:

Herrn Matthias Christoph
Tel.: 05321-7591-73 60
***@***.***


Viele Grüße aus Goslar,
Sebastian Schimansky
Leiter IT-Abteilung, Entwicklung

Tel.: +49 (0) 5321-7591-62
Fax: +49 (0) 5321-7591-69

TMA TourismusMarketing Agentur GmbH | Spitalstraße 1 | D-38640 Goslar | www.tourismus-agentur.de |Sitz der Gesellschaft: Goslar | Geschäftsführer: Ralf Hummel | Ust-IdNr. DE 233056626 | HRB 111371 - AG Braunschweig



I've been doing the charge limit through HA, by monitoring the battery level that the API provides and stopping my EVSE when the target is reached. The car is set to 100% all the time so that HA can control it.
