### ISSUE TITLE
Latest update appears to have added the same car twice

### ISSUE THREAD

**Issue by Redding43** [pypolestar/polestar_api#204]
V1.8.0

now showing two devices (vehicles) with the same name. The original entities are now all showing as unknown.

![IMG_3890](https://github.com/user-attachments/assets/e9bf768b-47e9-4c3e-9396-04f6f01839be)

**Comment by jschlyter** [comment]
The entity IDs has change as part of 1.8.0, just delete the unknown device and you should be all good.

**Comment by mariwing** [comment]
How can i delete the unknown device? Since it is not listed as a separate device on the integration page I don't know of anywhere to delete it? And since naming has changed, i would really like to delete the old device so I can rename the new one to the same name at the old had so I don't need to update many automations and dashboards.

**Comment by Redding43** [comment]
I had the same problem and could not delete the device, so I reinstalled the integration. This removed the old device and the new device and entities use the same names as they previously were and all of my automations et cetera started working again when no further changes.

**Comment by mariwing** [comment]
I tried the same, but that just ended with no device created at all, just the entities. And they all got the new name based on last digits in vin. So since re-adding did not create a device I had no device I could rename and as a consequence update all the sensor names as well. So now it seems that I need to rename 33 entities. 

Happy that someone has taken over this integration so I will not complain too loudly but I hope that these type of changes will not happen again :-)

**Comment by kp-bit** [comment]
> I tried the same, but that just ended with no device created at all, just the entities. And they all got the new name based on last digits in vin. So since re-adding did not create a device I had no device I could rename and as a consequence update all the sensor names as well. So now it seems that I need to rename 33 entities.
> 
Renaming to just "Polestar" and selecting to update all entities worked perfectly for me...

**Comment by laurencei** [comment]
I had to delete the intergration and add it again to remove the second car.
